---
title: "Visualizations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualizations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


**Page under construction**


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
suppressPackageStartupMessages({
  library(cevomod)
  library(tidyverse)
})

cd <- test_data
cd
```


# VAF spectra

```{r}
plot_SFS(cd) +
  aes(fill = sex) +
  scale_fill_manual(values = c(male = "#DD4124", female = "#00496F")) +
  labs(title = "Variant Allele Frequency Spectrum")
```


```{r}
plot_SFS(cd, geom = "line") +
  aes(color = sample_id) +
  labs(title = "Variant Allele Frequency Spectrum") +
  theme_minimal()
```

# Cumulative tails

```{r, fig.width=7, fig.height=5}
plot_cumulative_tails(cd, size = 0.5, scale_y = FALSE)
```

# M(f) ~ 1/f

```{r}
plot_Mf_1f(cd)
```

# VAF spectra with mutation annotation

```{r}
plot_SFS(cd) +
  layer_mutations(cd, drivers = "BRCA")
# 
# plot_SFS(tcga_brca_test) +
#   layer_mutations(tcga_brca_test, drivers = "BRCA", shape = "impact")
```

# Mutation plots

```{r}
plot_mutations(cd, drivers = "BRCA")
```

# Plot models

```{r}
cd |> 
  fit_powerlaw_tail_optim() |> 
  fit_subclones() |> 
  plot_models() +
  aes(fill = sex) +
  scale_fill_manual(values = c(male = "#DD4124", female = "#00496F")) +
  labs(title = "Models")
```


